### ISSUE TITLE
Hide username from types location

### ISSUE THREAD

**Issue by sg-chris** [scenery-io/cavalry-types#5]
A slightly niche request but I don't script without Stallion (!) and the Types so always add this to the top of my files via the VS Code Extension (Insert Cavalry Types):

`/// <reference path="/Users/[myUserName]/.vscode/extensions/scenery.cavalry-bridge-0.2.5/node_modules/@scenery/cavalry-types/index.d.ts"/>`

I'm currently using this to write some scripts that will ship with Cavalry so, because I don't really want my username included, I'm removing this line from the final script. This is fine but if I then need to go back and update something I'm adding it back and then removing it again.

I think it would be a good thing to be able to keep this in (for convenience and for 'advertising' Stallion) so would it be possible to abstract the user name within the file path in some way (via a local configuration?) so that it's not included in the actual script?

This would also mean (in theory) anyone opening it and editing/improving it would be able to use it without needing to change it.

**Comment by Klustre** [comment]
In your case I would keep a folder where all the scripts are saved. Follow the [installation](https://github.com/scenery-io/cavalry-types?tab=readme-ov-file#installation) and [Typescript](https://github.com/scenery-io/cavalry-types?tab=readme-ov-file#typescript-config) instructions. Then you won't need that comment anymore and you'll still get auto-completion. DM me on Discord if you need help setting this up.

The other option is to install VSCode for all users. On OSX you'd move the app to `/Applications` instead of `/Users/User/Applications`. On Windows you'd use the System Installer from the [download](https://code.visualstudio.com/download) page.

Every user will have to insert that comment for themselves because of their unique setup (user name and Stallion version).
